---
- name: Configurar Nginx en servidores web
  hosts: servers-nginx
  become: true
  roles:
    - geerlingguy.nginx

- name: Configurar base de datos con MySQL
  hosts: server-mysql
  become: true
  roles:
    - geerlingguy.mysql

- name: Instalar datadog
  hosts: servers
  become: true
  roles:
    - datadog.datadog
  vars:
    datadog_api_key: "<YOUR_DD_API_KEY>"
